name: PHP Composer

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    env:
      XDEBUG_MODE: coverage
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3



    # composer cache
    - name: Remove composer lock
      run: rm composer.lock

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Setup PHPunit
      run: composer install -n

    - name: Install Google Cloud Storage
      run: composer require google/cloud-storage

#    - name: Run unit tests
#      run: ../vendor/bin/phpunit --no-coverage
#      working-directory: tst

    - name: Install Xdebug
      run: sudo apt-get install -y php-xdebug
    
    - name: couverture sous format xml
      run: ../vendor/bin/phpunit --coverage-cobertura=my-cobertura-coverage.xml
      working-directory: tst

    - name: Code Coverage Summary Report
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
          filename: ./tst/my-cobertura-coverage.xml
          format: markdown
          output: both
          badge: true

    - name: echo code coverage
      run: cat code-coverage-results.md >> $GITHUB_STEP_SUMMARY

    - name: install phpcs
      run: curl -OL https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar

    - name: use phpcs
      run: php phpcs.phar --report-file=phpcs-res.txt . || true

    - name: Commit changes
      run: |
        git config --global user.email "nat2013@laposte.net"
        git config --global user.name "Almasty007"
        git add phpcs-res.txt
        git commit -m "ajout du phpcs-res"
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    
    
