name: PHP Composer

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    env:
      XDEBUG_MODE: coverage
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3



    # composer cache
    - name: Remove composer lock
      run: rm composer.lock

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v4
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Setup PHPunit
      run: composer install -n

    - name: Install Google Cloud Storage
      run: composer require google/cloud-storage

    - name: Run unit tests
      run: ../vendor/bin/phpunit --no-coverage
      working-directory: tst

    - name: Install Xdebug
      run: sudo apt-get install -y php-xdebug
    
    - name: couverture sous format xml
      run: ../vendor/bin/phpunit --coverage-cobertura=my-cobertura-coverage.xml
      working-directory: tst

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    # - name: Run test suite
    #   run: composer run-script test
